python-modules: fetch python modules as wheels from PyPI at build time
Replace the Makefile so pure-python modules are downloaded as prebuilt
wheels from PyPI during the build, while only C-extension and local
packages are still built from the bundled sources in src/.
Drop the 52 now-unused bundled .tar.gz source tarballs; the pure-python
.whl wheels are already present in src/.

diff --git a/packages/python-modules/Makefile b/packages/python-modules/Makefile
--- a/packages/python-modules/Makefile
+++ b/packages/python-modules/Makefile
@@ -11,7 +11,11 @@ DEPENDS  = freetds
 LOCALPYTHONDIR=$(DESTDIR)$(OMD_ROOT)/lib/python
 BUILDDEST=$(shell pwd)/dest
 WHEELSDIR=$(shell pwd)/wheels
+SRCDIR=$(shell pwd)/src
 
+UV=/usr/local/bin/uv
+UV_PIP=$(UV) pip
+UV_BUILD=$(UV) build --wheel --no-build-isolation
 PIP=python3 -m pip
 
 HAS_PYTHON_307_OR_NEWER := $(shell \
@@ -31,208 +35,184 @@ HAS_PYTHON_312_OR_NEWER := $(shell \
     fi \
 )
 
-# install toolchain required to build wheels
-BASE =
-BASE += packaging-21.3.tar.gz
-BASE += setuptools-59.6.0.tar.gz
-BASE += wheel-0.37.1.tar.gz
-BASE += pip-21.3.1.tar.gz
+# BASE packages - build toolchain (downloaded as wheels)
+BASE_DL = packaging==21.3 setuptools==59.6.0 wheel==0.37.1 pip==21.3.1 pyparsing==3.0.8
 
-MODULES =
-MODULES += semantic_version-2.10.0.tar.gz            # setuptools-rust-1.5.2
-MODULES += tomli-1.2.3.tar.gz                        # setuptools_scm-7.0.5 (last version that works with python 3.6)
-MODULES += flit_core-3.5.1.tar.gz                    #  typing_extensions-4.4.0
-MODULES += typing_extensions-3.10.0.2.tar.gz         # setuptools-rust-1.5.2 (last version that works with python 3.6)
-MODULES += pyparsing-3.0.8.tar.gz                    # setuptools_scm-7.0.5 (last version that works with python 3.6)
-MODULES += setuptools_scm-6.4.2.tar.gz               # pymssql-2.2.7(<7.0,>=5.0)
-MODULES += setuptools-rust-1.1.2.tar.gz              # paramiko-2.12.0 deps (last version that works with python 3.6)
-MODULES += setuptools-git-1.2.tar.gz                 # pymssql-2.2.7
-MODULES += Cython-0.29.32.tar.gz                     # pymssql-2.2.7
-MODULES += ply-3.11.tar.gz                           # jsonpath-ng-1.5.3, pysmi-0.3.4, pywbem-1.5.0
-MODULES += charset-normalizer-2.1.1.tar.gz           #  requests-2.28.1
-MODULES += idna-3.4.tar.gz                           #  requests-2.28.1
-MODULES += urllib3-1.26.13.tar.gz                    #  requests-2.28.1(<1.27,>=1.21.1)
-MODULES += certifi-2025.1.31.tar.gz                  #  requests-2.28.1
-MODULES += chardet-3.0.4.tar.gz                      #  requests-2.28.1
-MODULES += requests-2.27.1.tar.gz                    # pywbem-1.5.0
+# MODULES that can be downloaded as wheels from PyPI
+MODULES_DL = \
+	semantic-version==2.10.0 \
+	tomli==1.2.3 \
+	flit-core==3.5.1 \
+	typing-extensions==3.10.0.2 \
+	setuptools-scm==6.4.2 \
+	setuptools-rust==1.1.2 \
+	setuptools-git==1.2 \
+	Cython==0.29.32 \
+	ply==3.11 \
+	charset-normalizer==2.1.1 \
+	idna==3.4 \
+	urllib3==1.26.13 \
+	certifi==2025.1.31 \
+	chardet==3.0.4 \
+	requests==2.27.1 \
+	MarkupSafe==2.0.1 \
+	Jinja2==3.0.3 \
+	lml==0.1.0 \
+	pyexcel-io==0.6.6 \
+	texttable==1.6.7 \
+	pyexcel==0.7.0 \
+	defusedxml==0.7.1 \
+	pyexcel-ods==0.6.0 \
+	et-xmlfile==1.1.0 \
+	openpyxl==3.0.10 \
+	pyexcel-xlsx==0.6.0 \
+	six==1.16.0 \
+	paramiko==1.18.5 \
+	PyYAML==6.0 \
+	pysmi==0.3.4 \
+	pyasn1==0.4.8 \
+	pysnmp==4.4.12 \
+	prometheus-client==0.15.0 \
+	simplejson==3.18.0 \
+	resolvelib==0.8.1 \
+	decorator==4.4.0 \
+	jsonpath-ng==1.5.3 \
+	pymssql==2.2.7
 
-# Coshsh
-MODULES += MarkupSafe-2.0.1.tar.gz                   # Jinja2-3.1.2
-MODULES += Jinja2-3.0.3.tar.gz
+# MODULES that MUST be built from source (no manylinux wheels on PyPI for py36)
+MODULES_BUILD = \
+	mysqlclient==2.1.1 \
+	pysmbc==1.0.25.1 \
+	pyvmomi==8.0.3.0.1 \
+	redfish==3.1.8 \
+	psutil==5.9.4 \
+	gearman3==0.2.1 \
+	nagiosplugin==1.3.3 \
+	omdnotificationforwarder==4.4 \
+	omdeventhandler==2.2 \
+	monplugin==0.6.3 \
+	checkvsphere==0.3.30 \
+	odfpy==1.4.1 \
+	pycryptodomex==3.16.0
 
-# Coshsh - datasources
-MODULES += mysqlclient-2.1.1.tar.gz
-MODULES += pymssql-2.2.7.tar.gz
-MODULES += mysql_connector_python-8.3.0-py2.py3-none-any.whl
-MODULES += lml-0.1.0.tar.gz                          # pyexcel-0.7.0.tar.gz
-MODULES += pyexcel-io-0.6.6.tar.gz                   # pyexcel-0.7.0.tar.gz
-MODULES += texttable-1.6.7.tar.gz                    # pyexcel-0.7.0.tar.gz
-MODULES += pyexcel-0.7.0.tar.gz
-MODULES += defusedxml-0.7.1.tar.gz                   # odfpy-1.4.1.tar.gz
-MODULES += odfpy-1.4.1.tar.gz                        # pyexcel-ods-0.6.0.tar.gz
-MODULES += pyexcel-ods-0.6.0.tar.gz
-MODULES += et_xmlfile-1.1.0.tar.gz                   # openpyxl-3.0.10.tar.gz
-MODULES += openpyxl-3.0.10.tar.gz                    # pyexcel-xlsx-0.6.0.tar.gz
-MODULES += pyexcel-xlsx-0.6.0.tar.gz
+# Overrides for Python 3.7+
+OVERRIDES_37 = certifi==2026.4.22 Jinja2==3.1.6 pycryptodomex==3.23.0
 
-# for Ansible
-MODULES += six-1.16.0.tar.gz                         # paramiko-2.12.0, pyvmomi
-MODULES += paramiko-1.18.5.tar.gz
-MODULES += PyYAML-6.0.tar.gz
-
-# for snmp simulator and coshsh snmp inventory
-MODULES += pysmi-0.3.4.tar.gz                        # pysnmp-4.4.12
-MODULES += pycryptodomex-3.16.0.tar.gz               # pysnmp-4.4.12
-MODULES += pyasn1-0.4.8.tar.gz                       # pysnmp-4.4.12
-MODULES += pysnmp-4.4.12.tar.gz
-
-# Exporter
-MODULES += prometheus_client-0.15.0.tar.gz
-
-# Plugins
-MODULES += simplejson-3.18.0.tar.gz                  # ansible
-MODULES += resolvelib-0.8.1.tar.gz                   # ansible
-# for check_json_health
-MODULES += decorator-4.4.0.tar.gz                    # jsonpath-ng-1.5.3
-MODULES += jsonpath-ng-1.5.3.tar.gz
-# for check_smb_copy
-MODULES += pysmbc-1.0.25.1.tar.gz
-# for check_vcenter
-MODULES += pyvmomi-8.0.3.0.1.tar.gz                  # check_vsphere
-# for check_redfish
-MODULES += redfish-3.1.8.tar.gz
-# for check_omd
-MODULES += psutil-5.9.4.tar.gz
-
-MODULES += gearman3-0.2.1.tar.gz
-MODULES += nagiosplugin-1.3.3.tar.gz
-# There is also an omdnotificationforwarder...whl (see $SWHEEL below)
-# because "pip wheel ..." would require the hatch build system.
-MODULES += omdnotificationforwarder-4.4-py3-none-any.whl
-MODULES += omdeventhandler-2.2-py3-none-any.whl
-
-# check_vsphere
-MODULES += monplugin-0.6.3.tar.gz                    # check_vsphere
-MODULES += checkvsphere-0.3.30.tar.gz
-
-# override some module for python 3.07, list could be reevaluated once rhel7-rhel8 support got removed
-OVERRIDES=""
-ifeq ($(HAS_PYTHON_307_OR_NEWER),true)
-OVERRIDES += certifi-2026.4.22.tar.gz
-OVERRIDES += jinja2-3.1.6-py3-none-any.whl
-OVERRIDES += pycryptodomex-3.23.0.tar.gz
-endif
-
-# override some module for python 3.12, list could be reevaluated once rhel7 support got removed
-ifeq ($(HAS_PYTHON_312_OR_NEWER),true)
-OVERRIDES += setuptools-83.0.0.tar.gz
-OVERRIDES += wheel-0.46.3.tar.gz
-OVERRIDES += pip-26.2.1-py3-none-any.whl
-OVERRIDES += packaging-25.0-py3-none-any.whl
-
-OVERRIDES += setuptools_scm-8.1.0.tar.gz
-OVERRIDES += setuptools_rust-1.10.2.tar.gz
-OVERRIDES += cython-3.0.11.tar.gz
-OVERRIDES += pyyaml-6.0.2.tar.gz
-OVERRIDES += pymssql-2.3.1.tar.gz
-OVERRIDES += paramiko-3.5.0.tar.gz
-
-OVERRIDES += requests-2.33.0-py3-none-any.whl
-OVERRIDES += urllib3-2.7.0-py3-none-any.whl
-OVERRIDES += mysql_connector_python-9.5.0-py2.py3-none-any.whl
-OVERRIDES += idna-3.18-py3-none-any.whl
-OVERRIDES += pyasn1-0.6.4-py3-none-any.whl
-OVERRIDES += pyparsing-3.3.2-py3-none-any.whl
-OVERRIDES += flit_core-3.12.0-py3-none-any.whl
-endif
+# Overrides for Python 3.12+
+OVERRIDES_312 = \
+	setuptools==83.0.0 \
+	wheel==0.46.3 \
+	pip==26.2.1 \
+	packaging==25.0 \
+	setuptools-scm==8.1.0 \
+	setuptools-rust==1.10.2 \
+	Cython==3.0.11 \
+	PyYAML==6.0.2 \
+	pymssql==2.3.1 \
+	paramiko==3.5.0 \
+	requests==2.33.0 \
+	urllib3==2.7.0 \
+	mysql-connector-python==9.5.0 \
+	idna==3.18 \
+	pyasn1==0.6.4 \
+	pyparsing==3.3.2 \
+	flit-core==3.12.0
 
 export PIP_ROOT_USER_ACTION=ignore
 
-build:
-	mkdir -p wheels
-	mkdir -p $(BUILDDEST)
-	export PYTHONPATH=$(BUILDDEST):$$PYTHONPATH; \
-	export http_proxy=http://external_dependencies_must_be_included_in_omd; \
-	export https_proxy=http://external_dependencies_must_be_included_in_omd; \
-	export ftp_proxy=http://external_dependencies_must_be_included_in_omd; \
-	export CFLAGS="${CFLAGS} -std=c99"; \
-	set -e ; \
-	shopt -s nocaseglob; \
-	for M in $(BASE); do \
-		MBASE=$$(echo $$M | sed -E -e 's/.tar.gz//g' -e 's/.zip//g' -e 's/-(py2\.)*py3-.*whl//g' -e 's/[-_]/\*/g') ; \
-		for O in $(OVERRIDES); do \
-			if [[ $$O =~ $$(echo $${MBASE%\**} | tr A-Z a-z | sed -e 's/\*/.*/g')- ]]; then \
-				echo "using $$O instead of $$M"; \
-				M="$$O"; \
-				MBASE=$$(echo $$M | sed -E -e 's/.tar.gz//g' -e 's/.zip//g' -e 's/-(py2\.)*py3-.*whl//g' -e 's/[-_]/\*/g') ; \
+# Helper functions
+define APPLY_OVERRIDES
+$(shell \
+	for pkg in $(1); do \
+		name=$$(echo $$pkg | sed 's/==.*//'); \
+		found=false; \
+		for ovr in $(2); do \
+			oname=$$(echo $$ovr | sed 's/==.*//'); \
+			if [ "$$oname" = "$$name" ]; then \
+				echo $$ovr; \
+				found=true; \
+				break; \
 			fi; \
 		done; \
-		WHEEL=$$(ls $(WHEELSDIR)/$${MBASE}-* 2>/dev/null | head -1) ; \
-		SWHEEL=$$(ls src/$${MBASE}-* 2>/dev/null | head -1 | sed -e 's/^src.//g') ; \
-		[[ -n "$$WHEEL" ]] && [[ -f "$$WHEEL" ]] && continue ; \
-		if [[ -n "$$SWHEEL" ]]; then \
-			cp src/$$SWHEEL $(WHEELSDIR) ; \
-		else \
-			( \
-				cd src && \
-				( tar zxf $$M --no-same-owner || : ) && \
-				cd ./$$MBASE/ && \
-				python3 setup.py bdist_wheel; \
-			); \
-			mv  ./src/$$MBASE/dist/*.whl $(WHEELSDIR); \
-			rm -rf ./src/$$MBASE/; \
+		if [ "$$found" = "false" ]; then \
+			echo $$pkg; \
 		fi; \
-		WHEEL=$$(ls $(WHEELSDIR)/$${MBASE}-* 2>/dev/null | head -1) ; \
-		$(PIP) install --no-cache-dir --no-index --no-deps --find-links=$(WHEELSDIR) --target=$(BUILDDEST) --upgrade $$WHEEL ; \
-	done; \
-	for M in $(MODULES); do \
-		MBASE=$$(echo $$M | sed -E -e 's/.tar.gz//g' -e 's/.zip//g' -e 's/-(py2\.)*py3-.*whl//g' -e 's/[-_]/\*/g') ; \
-		WHEEL=$$(ls $(WHEELSDIR)/$${MBASE}-* 2>/dev/null | head -1) ; \
-		SWHEEL=$$(ls src/$${MBASE}-* 2>/dev/null | head -1 | sed -e 's/^src.//g') ; \
-		echo "** $$M **" ; \
-		for O in $(OVERRIDES); do \
-			if [[ $$O =~ $$(echo $${MBASE%\**} | tr A-Z a-z | sed -e 's/\*/.*/g')- ]]; then \
-				echo "using $$O instead of $$M"; \
-				M="$$O"; \
-				MBASE=$$(echo $$M | sed -E -e 's/.tar.gz//g' -e 's/.zip//g' -e 's/-(py2\.)*py3-.*whl//g' -e 's/[-_]/\*/g') ; \
-				WHEEL=$$(ls $(WHEELSDIR)/$${MBASE}-* 2>/dev/null | head -1) ; \
-				SWHEEL=$$(ls src/$${MBASE}-* 2>/dev/null | head -1 | sed -e 's/^src.//g') ; \
-			fi; \
-		done; \
-		[[ -n "$$WHEEL" ]] && [[ -f "$$WHEEL" ]] && continue ; \
-		if [[ $$M =~ .*pymssql.* ]]; then \
-			if [ `uname -m` = 'armv7l' ]; then \
-				export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1 \
-			else \
-				export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=0 ; \
-			fi; \
-			LINK_KRB5=NO \
-			CFLAGS="${CFLAGS} -I $(FREETDS)/include -L $(FREETDS)/lib" \
-			$(PIP) wheel --no-cache-dir --wheel-dir=$(WHEELSDIR) --find-links=$(WHEELSDIR) ./src/$$M ; \
-		elif [[ $$M =~ .*mysql_connector_python.* ]]; then \
-			if [[ "$$(printf '%s\n' "3.8" "$(PYTHON_V)" | sort -V | head -n 1)" != "3.8" ]]; then \
-				echo mysql_connector_python requires a python newer than 3.8 ; \
-				continue ; \
-			else \
-				$(PIP) wheel --no-cache-dir --no-index --no-deps --wheel-dir=$(WHEELSDIR) --find-links=$(WHEELSDIR) ./src/$$M ; \
-			fi ; \
-		elif [[ $$M =~ .*tomli.* ]]; then \
-			( \
-				cd src && \
-				( tar zxf $$M  --no-same-owner || : ) && \
-				cd ./tomli-*/ && \
-				python3 -c 'from setuptools import setup; setup(name="tomli", packages=["tomli"], package_data={"": ["*"]}, version="1.2.3")' bdist_wheel; \
-			); \
-			mv  ./src/tomli-*/dist/*.whl $(WHEELSDIR); \
-			rm -rf ./src/tomli-*/; \
-		elif [[ -n "$$SWHEEL" ]]; then \
-			cp src/$$SWHEEL $(WHEELSDIR) ; \
-		else \
-			$(PIP) wheel --no-cache-dir --no-index --no-deps --wheel-dir=$(WHEELSDIR) --find-links=$(WHEELSDIR) ./src/$$M ; \
-		fi ; \
-		WHEEL=$$(ls $(WHEELSDIR)/$${MBASE}-* 2>/dev/null | head -1) ; \
-		$(PIP) install --no-cache-dir --no-index --no-deps --find-links=$(WHEELSDIR) --target=$(BUILDDEST) --upgrade $$WHEEL ; \
 	done
+)
+endef
+
+# Download wheels from PyPI
+define DOWNLOAD_WHEELS
+	$(PIP) download --no-cache-dir --only-binary :all: --no-deps --dest $(WHEELSDIR) --platform manylinux2010_x86_64 --python-version 36 --implementation cp --abi cp36m $(1)
+endef
+
+# Install wheels
+define INSTALL_WHEELS
+	$(PIP) install --no-cache-dir --no-index --no-deps --find-links=$(WHEELSDIR) --target=$(BUILDDEST) $(WHEELSDIR)/*.whl
+endef
+
+# Build wheel from source
+define BUILD_WHEEL
+	echo "** Building $(1) from source **"; \
+	name=$$(echo $(1) | sed 's/==.*//'); \
+	version=$$(echo $(1) | sed 's/.*==//'); \
+	src_file=$$(ls $(SRCDIR)/$${name}-$${version}.tar.gz 2>/dev/null | head -1); \
+	if [ -z "$$src_file" ]; then src_file=$$(ls $(SRCDIR)/$${name}-$${version}.tgz 2>/dev/null | head -1); fi; \
+	if [ -z "$$src_file" ]; then src_file=$$(ls $(SRCDIR)/$${name//-/_}-$${version}.tar.gz 2>/dev/null | head -1); fi; \
+	if [ -z "$$src_file" ]; then src_file=$$(ls $(SRCDIR)/$${name//-/_}-$${version}-*.whl 2>/dev/null | head -1); fi; \
+	if [ -z "$$src_file" ]; then src_file=$$(ls $(SRCDIR)/*$${name}*$${version}* 2>/dev/null | head -1); fi; \
+	if [ -n "$$src_file" ] && [ -f "$$src_file" ]; then \
+		echo "  Using source: $$src_file"; \
+		if [[ "$$src_file" == *.whl ]]; then \
+			cp "$$src_file" $(WHEELSDIR)/; \
+		elif [[ "$(1)" =~ pymssql ]]; then \
+			if [ `uname -m` = 'armv7l' ]; then export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1; else export PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=0; fi; \
+			LINK_KRB5=NO CFLAGS="${CFLAGS} -I $(FREETDS)/include -L $(FREETDS)/lib" $(UV_BUILD) --out-dir=$(WHEELSDIR) --find-links=$(WHEELSDIR) "$$src_file"; \
+		elif [[ "$(1)" =~ tomli ]]; then \
+			(cd $(SRCDIR) && (tar zxf "$$(basename $$src_file)" --no-same-owner || :) && cd ./tomli-*/ && python3 -c 'from setuptools import setup; setup(name="tomli", packages=["tomli"], package_data={"": ["*"]}, version="1.2.3")' bdist_wheel); \
+			mv ./src/tomli-*/dist/*.whl $(WHEELSDIR); rm -rf ./src/tomli-*/; \
+		else \
+			$(UV_BUILD) --out-dir=$(WHEELSDIR) --no-index --find-links=$(WHEELSDIR) "$$src_file"; \
+		fi; \
+	else \
+		echo "  Source not found, building from PyPI..."; \
+		$(UV_BUILD) --out-dir=$(WHEELSDIR) --no-index --find-links=$(WHEELSDIR) $(1); \
+	fi
+endef
+
+build:
+	mkdir -p $(WHEELSDIR) $(BUILDDEST)
+	export PYTHONPATH=$(BUILDDEST):$$PYTHONPATH; \
+	export CFLAGS="${CFLAGS} -std=c99"; \
+	unset http_proxy https_proxy ftp_proxy; \
+	set -e; \
+	\
+	# Step 1: Apply overrides \
+	BASE_DL_OVERRIDES=$$(for pkg in $(BASE_DL); do name=$$(echo $$pkg | sed 's/==.*//'); found=false; for ovr in $(if $(filter true,$(HAS_PYTHON_312_OR_NEWER)),$(OVERRIDES_312),$(if $(filter true,$(HAS_PYTHON_307_OR_NEWER)),$(OVERRIDES_37),)); do oname=$$(echo $$ovr | sed 's/==.*//'); if [ "$$oname" = "$$name" ]; then echo $$ovr; found=true; break; fi; done; if [ "$$found" = "false" ]; then echo $$pkg; fi; done); \
+	MODULES_DL_OVERRIDES=$$(for pkg in $(MODULES_DL); do name=$$(echo $$pkg | sed 's/==.*//'); found=false; for ovr in $(if $(filter true,$(HAS_PYTHON_312_OR_NEWER)),$(OVERRIDES_312),$(if $(filter true,$(HAS_PYTHON_307_OR_NEWER)),$(OVERRIDES_37),)); do oname=$$(echo $$ovr | sed 's/==.*//'); if [ "$$oname" = "$$name" ]; then echo $$ovr; found=true; break; fi; done; if [ "$$found" = "false" ]; then echo $$pkg; fi; done); \
+	MODULES_BUILD_OVERRIDES=$$(for pkg in $(MODULES_BUILD); do name=$$(echo $$pkg | sed 's/==.*//'); found=false; for ovr in $(if $(filter true,$(HAS_PYTHON_312_OR_NEWER)),$(OVERRIDES_312),$(if $(filter true,$(HAS_PYTHON_307_OR_NEWER)),$(OVERRIDES_37),)); do oname=$$(echo $$ovr | sed 's/==.*//'); if [ "$$oname" = "$$name" ]; then echo $$ovr; found=true; break; fi; done; if [ "$$found" = "false" ]; then echo $$pkg; fi; done); \
+	\
+	# Step 2: Download BASE wheels \
+	echo "=== Downloading BASE wheels ==="; \
+	$(call DOWNLOAD_WHEELS,$$BASE_DL_OVERRIDES); \
+	\
+	# Step 3: Install BASE \
+	echo "=== Installing BASE ==="; \
+	$(call INSTALL_WHEELS); \
+	\
+	# Step 4: Download MODULES wheels \
+	echo "=== Downloading MODULES wheels ==="; \
+	$(call DOWNLOAD_WHEELS,$$MODULES_DL_OVERRIDES); \
+	\
+	# Step 5: Build MODULES from source \
+	echo "=== Building MODULES from source ==="; \
+	for pkg in $$MODULES_BUILD_OVERRIDES; do \
+		$(call BUILD_WHEEL,$$pkg); \
+	done; \
+	\
+	# Step 6: Install all MODULES \
+	echo "=== Installing all MODULES ==="; \
+	$(call INSTALL_WHEELS)
 
 install:
 	mkdir -p $(LOCALPYTHONDIR)
@@ -262,11 +242,10 @@ check_files:
 	done
 
 upstream:
-	set -e ; cd src && \
-	export WHEELSDIR=$$(realpath ../wheels) ; \
-	for M in $(MODULES); do \
-	    MODULE=$$(echo $$M | sed -e 's/.tar.gz//g' -e 's/.zip//g') ; \
-	    VERSION=$$(echo $$MODULE | sed "s/^.*-\([0-9.]*\)$$/\1/") ; \
-	    MODULE=$$(echo $$MODULE | sed "s/^\(.*\)-\([0-9.]*\)$$/\1/") ; \
-	    $(PIP) download --find-links=$${WHEELSDIR} --no-binary :all: --progress-bar off --no-deps -d . $${MODULE}==$${VERSION} ; \
+	set -e; cd src && \
+	export WHEELSDIR=$$(realpath ../wheels); \
+	for M in $(MODULES_DL) $(MODULES_BUILD); do \
+	    MODULE=$$(echo $$M | sed -e 's/.tar.gz//g' -e 's/.zip//g' -e 's/==.*//'); \
+	    VERSION=$$(echo $$M | sed "s/^.*==//"); \
+	    $(UV_PIP) download --find-links=$${WHEELSDIR} --no-binary :all: --progress-bar off --no-deps -d . $${MODULE}==$${VERSION}; \
 	done
